### ISSUE TITLE
AWAIT ERROR

### ISSUE THREAD

**Issue by Shaktigupta931** [talkpython/modern-apis-with-fastapi#17]
ch04-language-foundations/async/async_scrape
[program.py](https://github.com/talkpython/modern-apis-with-fastapi/blob/main/ch04-language-foundations/async/async_scrape/program.py)

await mising  in get_title_range function 

    for n, t in tasks:
        html = await t
        title = await get_title(html, n)
        print(Fore.WHITE + f"Title found: {title}", flush=True)

**Comment by mikeckennedy** [comment]
Hi @Shaktigupta931 Thanks for the issue. However, this is inaccurate. Notice the definition of `get_title()`:

```python
def get_title(html: str, episode_number: int) -> str:
    print(Fore.CYAN + f"Getting TITLE for episode {episode_number}", flush=True)
    soup = bs4.BeautifulSoup(html, 'html.parser')
    header = soup.select_one('h1')
    if not header:
        return "MISSING"

    return header.text.strip()
```

It's not async so you should not await it. I don't know if that's a runtime error or will just be ignored. I suspect it's an error. Either way, never await regular functions (`def` rather than `async def` ones).
