### ISSUE TITLE
Course video ch.5 vid 14/14 "Concept: Async API methods" - slides vs. repo descrepancy

### ISSUE THREAD

**Issue by sergei3000** [talkpython/modern-apis-with-fastapi#8]
The code starting with `async with` block in the openweathermap service in the repo looks like this:
```python
    async with httpx.AsyncClient() as client:
        resp = await client.get(url)
        resp.raise_for_status()

    data = resp.json()
    forecast = data['main']
    return forecast
```
Notice the final three lines which are not indented.
See https://github.com/talkpython/modern-apis-with-fastapi/blob/main/ch05-a-realistic-api/services/openweather_service.py
But the slide shown at 00:35 in the video tells that those lines should be indented and thus included in the `async with` block.
So which is the right way to do this?

**Comment by mikeckennedy** [comment]
Hi @sergei3000 Doesn't matter. Do you want to:

## Above version

- Open client
- Get data
- **close client**
- work with data

or

## Slides version

- Open client
- Get data
- work with data
- **close client**

Because the working with data part has no async, it doesn't matter. Probably what's listed in this issue is better just to tidy up sooner.
