### ISSUE TITLE
Feature request: asyncronous database queries

### ISSUE THREAD

**Issue by sergei3000** [talkpython/modern-apis-with-fastapi#9]
You have awesome examples on working with external API's asynchronously using httpx.
It would be great if there was a small video on how to work with SQL/noSQL databases in this manner.

**Comment by mikeckennedy** [comment]
Hi @sergei3000 Thanks for the idea. When I created this course, SQLAlchemy was still only sync. But recently went to offer an async option as well. I spend a lot of time on doing async/await with views + SQLAlchemy in the follow on course at https://talkpython.fm/fastapi-web

I generally don't update the courses with new chapters once they are done because it makes them disjointed unless it's needed to fix something that's changed to add to what we are already doing that was unclear. Since we didn't touch DBs in this one, I don't think adding that makes sense here.

**Comment by sergei3000** [comment]
@mikeckennedy That course you are writing about seems interesting. But from looking into its contents I don't see any videos on schema migration in it (something like Alembic probably). Which is a very important topic in the context of working with databases.

**Comment by mikeckennedy** [comment]
Hi. No we don't cover Alembic although it is important. Our Flask & Pyramid Data Driven Web Apps courses do dive deep into SQLAlchemy and Alembic.
